# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citypalapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=100)),
                ('suburb', models.CharField(default='', max_length=100)),
                ('lat', models.CharField(default='', max_length=100)),
                ('lng', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
